# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'AppleLogin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppleLogin
  pod 'FirebaseUI', '~> 8.0'
  pod 'FirebaseUI/Auth', '~> 8.0'
end
